CONFIG_GPIO=y

CONFIG_EARLY_CONSOLE=y
#CONFIG_SHELL=y

# Don't log printk() statements, they're meant for raw output to the console.
CONFIG_LOG_PRINTK=n
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_CBPRINTF_FP_SUPPORT=y


CONFIG_SENSOR=y

#CONFIG_ESP32_TEMP=y

CONFIG_DHT=y
CONFIG_DHT_LOCK_IRQS=y

CONFIG_LED_STRIP=y
CONFIG_LED_STRIP_LOG_LEVEL_DBG=y