CONFIG_GPIO=y

CONFIG_EARLY_CONSOLE=y
#CONFIG_SHELL=y

# Don't log printk() statements, they're meant for raw output to the console.
CONFIG_LOG_PRINTK=n
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_CBPRINTF_FP_SUPPORT=y


CONFIG_SENSOR=y

CONFIG_ESP32_TEMP=y

